version: "3"
services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - 80:5000
    depends_on:
      - db
    env_file:
      - .env.example
    volumes:
      - .:/usr/src/
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.example
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
